packages:
  - notepadd-core
  - notepadd-docs
  - notepadd-timekeeper
  - vite-plugins/child-process
  - vite-plugins/nearley
  - vite-plugins/package-json
  - vite-plugins/subvite
  - vite-plugins/vscode
  - vscode-notepadd
onlyBuiltDependencies:
  - esbuild
