@startuml bookkeeperState
hide empty description

Starting : \
Search for files\n\
Watch the files\n\
Spawn timekeeper
[*] --> Starting

Idling : Nothing to do
Starting --> Idling

Resetting : \
Send Update message\n\
Update bridge if open
Idling --> Resetting : Discover message
Resetting --> Idling

Processing : \
Process FS change\n\
Send Update message\n\
Update bridge if open
Idling --> Processing : FS changed
Processing --> Idling

Triggering : \
Signal the bridge if open\n\
Show message if not
Idling --> Triggering : Trigger message
Triggering --> Idling

Restarting : \
Mark bridge as stale if open\n\
Terminate timekeeper\n\
Spawn timekeeper
Idling --> Restarting : Restart requested
Restarting --> Idling

Stopping : \
Terminate timekeeper\n\
Mark bridge as stale if open\n\
Stop watching the files
Idling --> Stopping : Deactivation requested
Stopping --> [*]

@enduml
