@startuml packages

component "notepadd" as np {
	component "notepadd-core" as core {
		component "format" as core_fmt
		component "directives" as core_dir
	}
	note bottom of core: APIs: [None]

	component "vite-plugin-vscode" as vpv
	note bottom of vpv: APIs: Node.JS, Vite

	component "vite-plugin-nearley" as vpn
	note bottom of vpn: APIs: Node.JS, Vite

	component "vscode-notepadd" as vsc {
		component "vite.config" as vsc_vite
		vsc_vite -(0- vpv
		vsc_vite -(0- vpn
		note left of vsc_vite: APIs: Node.JS, Vite

		component "serializer" as vsc_serde
		vsc_serde -(0- core_fmt

		component "controller" as vsc_ctrl
		vsc_ctrl -(0- core_dir
	}
	note top of vsc: APIs: VS Code, Node.JS
}

@enduml
