@startuml packages

component "notepadd" as np {
	component "notepadd-core" as core {
		component "format" as core_fmt
		component "directives" as core_dir
		component "export" as core_exp
	}
	note bottom of core: APIs: [None]

	component "notepadd-timekeeper" as time
	note bottom of time: APIs: Node.JS
	time --(0-- core_fmt
	time --(0-- core_dir

	component "vscode-notepadd" as vsc {
		component "export" as vsc_exp
		vsc_exp --(0-- core_exp

		component "serializer" as vsc_serde
		vsc_serde --(0-- core_fmt

		component "controller" as vsc_ctrl
		vsc_ctrl --(0-- core_dir

		component "Bookkeeper" as vsc_book
		vsc_book --(0-- time

		component "Bridge" as vsc_bridge
		vsc_bridge --(0-- time
	}
	note top of vsc: APIs: VS Code, Node.JS
}

@enduml
