@startuml timekeeperState
hide empty description

Starting : Sends Discover message
[*] --> Starting : Spawned

Processing : \
Sets new directives up\n\
Tears old directives down
Starting --> Idling

Idling : Nothing to do
Processing --> Idling
Idling --> Processing : Update message

Triggering : \
Sends Trigger message if applicable\n\
Renews directive if applicable
Idling --> Triggering : Directive triggered
Triggering --> Idling

state "Checking for Suspense" as CheckingForSuspense : Check if interval took too long to reoccur
Idling --> CheckingForSuspense : Interval triggered
CheckingForSuspense --> Triggering : Suspense detected
CheckingForSuspense --> Idling

Idling --> [*] : Terminate message

@enduml
